# -*- coding: utf-8 -*-
"""deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YO3xpUdsV4AyhEFAjOda74lWm6vxPJj6
"""

!pip install streamlit

import streamlit as st
import tensorflow as tf
import numpy as np

# Load models
skintype_model = tf.keras.models.load_model('/content/drive/MyDrive/KBL/skintype.h5')
product_type_model = tf.keras.models.load_model('/content/drive/MyDrive/KBL/product_type.h5')

# Define functions for encoding
def encode_skintype(skintype):
    # Dummy encoding, replace with your logic
    return [0]  # Example encoding

def encode_product_type(product_type):
    # Dummy encoding, replace with your logic
    return [0]  # Example encoding

# App title
st.title("Rekomendasi Produk Skincare")

# Input fields
skintype_input = st.text_input("Masukkan Skin Type (misal: 'Oily, Sensitive'):")
product_type_input = st.text_input("Masukkan Product Type (misal: 'Moisturizer'):")

# Predict button
if st.button("Rekomendasikan Produk"):
    if skintype_input and product_type_input:
        # Encode inputs
        skintype_encoded = encode_skintype(skintype_input)
        product_type_encoded = encode_product_type(product_type_input)

        # Predict using models
        skintype_pred = skintype_model.predict(np.array([skintype_encoded]))
        product_type_pred = product_type_model.predict(np.array([product_type_encoded]))

        # Combine predictions or determine output
        # Modify this to suit your use case
        st.write(f"Prediksi Skin Type: {np.argmax(skintype_pred)}")
        st.write(f"Prediksi Product Type: {np.argmax(product_type_pred)}")
    else:
        st.error("Masukkan semua informasi yang diminta!")